apiVersion: apps/v1
kind: Deployment
metadata:
  name: fog-rollouts-api
  labels:
    app: fog-rollouts-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fog-rollouts-api
  template:
    metadata:
      labels:
        app: fog-rollouts-api
    spec:
      serviceAccountName: fog-rollouts
      containers:
        - name: fog-rollouts-api
          image: fog-rollouts
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          command: 
            - uvicorn 
            - api:app
            - --host 
            - "0.0.0.0"
            - --port 
            - "80"
