{{- if .Values.cloud -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: fog-rollouts-watcher
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: fog-rollouts
          containers:
          - name: fog-rollouts-watcher
            image: fog-rollouts-watcher
            imagePullPolicy: Never
            env:
            - name: FOG_ROLLOUTS_API_CLOUD
              value: {{ .Values.cloud.api_endpoint }}
            - name: FOG_ROLLOUTS_API_NAMESPACE
              value: {{ .Values.cloud.namespace }}
            - name: FOG_ROLLOUTS_API_LAYER
              value: {{ .Values.layer.api_endpoint }}
            - name: FOG_ROLLOUTS_NAMESPACE
              value: {{ .Release.Namespace }}
          restartPolicy: OnFailure
{{- end -}}