{{- if .Values.watcher -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: fog-rollouts-watcher
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: fog-rollouts
          containers:
          - name: fog-rollouts-watcher
            image: fog-rollouts-watcher
            imagePullPolicy: Never
            env:
            - name: FOG_ROLLOUTS_API_ENDPOINT
              value: {{ .Values.watcher.api.endpoint }}
            - name: FOG_ROLLOUTS_API_NAMESPACE
              value: {{ .Values.watcher.api.namespace }}
            - name: FOG_ROLLOUTS_NAMESPACE
              value: {{ .Values.watcher.namespace }}
          restartPolicy: OnFailure
{{- end -}}