apiVersion: paguos.io/v1alpha1
kind: FogRollout
metadata:
  name: cassandra-rollout
spec:
  version: v0.1.1
  deployments:
    cloud:
      replicas: 1
      containers:
        - name: fog-cassandra
          image: cassandra:3.0
          ports:
            - name: intra
              containerPort: 7000
            - name: tls
              containerPort: 7001
            - name: jmx
              containerPort: 7199
            - name: cql
              containerPort: 9042
            - name: thrift
              containerPort: 9160
          env:
            - name: CASSANDRA_CLUSTER_NAME
              value: cassandra-cluster
            - name: CASSANDRA_PASSWORD_SEEDER
              value: "yes"
            - name: CASSANDRA_PASSWORD
              value: mypassword
          readinessProbe:
            exec:
              command: [ "/bin/sh", "-c", "nodetool status | grep -E `hostname -i`" ]
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
    fog:
      replicas: 1
      containers:
        - name: fog-cassandra
          image: cassandra:3.0
          ports:
            - name: intra
              containerPort: 7000
            - name: tls
              containerPort: 7001
            - name: jmx
              containerPort: 7199
            - name: cql
              containerPort: 9042
            - name: thrift
              containerPort: 9160
          env:
            - name: CASSANDRA_CLUSTER_NAME
              value: cassandra-cluster
            - name: CASSANDRA_SEEDS
              value: "cassandra-rollout.cloud"
            - name: CASSANDRA_PASSWORD
              value: mypassword
          readinessProbe:
            exec:
              command: [ "/bin/sh", "-c", "nodetool status | grep -E `hostname -i`" ]
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
    edge:
      replicas: 1
      containers:
        - name: fog-cassandra
          image: cassandra:3.0
          ports:
            - name: intra
              containerPort: 7000
            - name: tls
              containerPort: 7001
            - name: jmx
              containerPort: 7199
            - name: cql
              containerPort: 9042
            - name: thrift
              containerPort: 9160
          env:
            - name: CASSANDRA_CLUSTER_NAME
              value: cassandra-cluster
            - name: CASSANDRA_SEEDS
              value: "cassandra-rollout.cloud"
            - name: CASSANDRA_PASSWORD
              value: mypassword
          readinessProbe:
            exec:
              command: [ "/bin/sh", "-c", "nodetool status | grep -E `hostname -i`" ]
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3