apiVersion: paguos.io/v1alpha1
kind: FogRollout
metadata:
  name: nginx-rollout
spec:
  version: v0.2.0
  deployments:
    cloud:
      replicas: 1
      containers:
        - name: fog-nginx
          image: nginx
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              port: 80
              scheme: HTTP
              path: /
    fog:
      replicas: 1
      containers:
        - name: fog-nginx
          image: nginx
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              port: 80
              scheme: HTTP
              path: /
