apiVersion: v1
kind: ServiceAccount
metadata:
  name: fog-rollouts
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fog-rollouts
rules:
  - apiGroups:
      - paguos.io
    resources:
      - fogrollouts
    verbs:
      - get
      - list
      - watch
      - update
      - patch
      - delete
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fog-rollouts
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fog-rollouts
subjects:
  - kind: ServiceAccount
    name: fog-rollouts
    namespace: default
