apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: fogrollouts.paguos.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: paguos.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                version:
                  type: string
                deployments:
                  type: object
                  properties:
                    cloud:
                      type: object
                      properties:
                        replicas:
                          type: integer
                        containers:
                          type: array
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                              image:
                                type: string
                              env:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    name:
                                      type: string
                                    value:
                                      type: string
                              ports:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    containerPort:
                                      type: integer
                              readinessProbe:
                                type: object
                                properties:
                                  httpGet:
                                    type: object
                                    properties:
                                      port:
                                        type: integer
                                      scheme:
                                        type: string
                                      path:
                                        type: string
                    fog:
                      type: object
                      properties:
                        replicas:
                          type: integer
                        containers:
                          type: array
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                              image:
                                type: string
                              env:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    name:
                                      type: string
                                    value:
                                      type: string
                              ports:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    containerPort:
                                      type: integer
                              readinessProbe:
                                type: object
                                properties:
                                  httpGet:
                                    type: object
                                    properties:
                                      port:
                                        type: integer
                                      scheme:
                                        type: string
                                      path:
                                        type: string
                    edge:
                      type: object
                      properties:
                        replicas:
                          type: integer
                        containers:
                          type: array
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                              image:
                                type: string
                              env:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    name:
                                      type: string
                                    value:
                                      type: string
                              ports:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    containerPort:
                                      type: integer
                              readinessProbe:
                                type: object
                                properties:
                                  httpGet:
                                    type: object
                                    properties:
                                      port:
                                        type: integer
                                      scheme:
                                        type: string
                                      path:
                                        type: string
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: fogrollouts
    # singular name to be used as an alias on the CLI and for display
    singular: fogrollout
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: FogRollout
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - fogrt
